package com.sopnobazz.demo.comon.base.constants;

import lombok.Getter;
import lombok.ToString;

/**
 * @version 1.0.0
 * @Project demo-management
 * @Author Md. Nayeemul Islam
 * @Since Aug 23, 2022
 */


@Getter
@ToString
public enum MasterMetaKey {
    ADDRESS_TYPE_BUSINESS_ADDRESS,
    ADDRESS_TYPE_HOME_ADDRESS,
    ADDRESS_TYPE_OFFICE_ADDRESS,
    ADDRESS_TYPE_PERMANENT_ADDRESS,
    ADDRESS_TYPE_PRESENT_ADDRESS,
    ADDRESS_TYPE_SHIPPING_ADDRESS,
    NOTIFICATION_CUSTOMER_SIGN_UP,
    NOTIFICATION_CUSTOMER_STATUS_CHANGE,
    NOTIFICATION_ORDER_CANCEL,
    NOTIFICATION_ORDER_DELIVERED,
    NOTIFICATION_ORDER_HALT,
    NOTIFICATION_ORDER_ORDER_CONFIRMATION,
    NOTIFICATION_ORDER_RETURN,
    ORDER_STATUS_TYPE_CANCEL,
    ORDER_STATUS_TYPE_COMPLETED,
    ORDER_STATUS_TYPE_DELIVERED,
    ORDER_STATUS_TYPE_HOLD,
    ORDER_STATUS_TYPE_PENDING,
    ORDER_STATUS_TYPE_PROCESSING,
    ORDER_STATUS_TYPE_RETURN,
    ORDER_STATUS_TYPE_SHIPPING,
    PAYMENT_GATEWAY_TYPE_AAMAR_PAY,
    PAYMENT_GATEWAY_TYPE_COD,
    PAYMENT_GATEWAY_TYPE_SSL_COMMERZ,
    PAYMENT_STATUS_TYPE_PAID,
    PAYMENT_STATUS_TYPE_PARTIALLY_PAID,
    PAYMENT_STATUS_TYPE_REFUNDED,
    PAYMENT_STATUS_TYPE_UNPAID,
    POLICY_TEMPLATE_PRIVACY,
    POLICY_TEMPLATE_REFUND,
    POLICY_TEMPLATE_SHIPPING,
    POLICY_TEMPLATE_TOS,
    QUANTITY_ADJUSTMENT_TYPE_CORRECTION,
    QUANTITY_ADJUSTMENT_TYPE_COUNT,
    QUANTITY_ADJUSTMENT_TYPE_DAMAGED,
    QUANTITY_ADJUSTMENT_TYPE_RECEIVED,
    QUANTITY_ADJUSTMENT_TYPE_RETURN_RESTOCK,
    REPORT_TYPE_ADVANCE,
    REPORT_TYPE_BASIC,
    REPORT_TYPE_STANDARD,
    SALES_CHANNEL_ONLINE_STORE,
    SALES_CHANNEL_POS,
    STORE_MENU_TYPE_CATEGORIES,
    STORE_MENU_TYPE_COLLECTIONS,
    STORE_MENU_TYPE_CUSTOM,
    STORE_MENU_TYPE_PAGES,
    SUPPORT_TYPE_EMAIL,
    SUPPORT_TYPE_IN_PERSON,
    SUPPORT_TYPE_LIVE_CHAT,
    SUPPORT_TYPE_PHONE,
    UNIT_FEET,
    UNIT_METER,
    WEBX_SERVICES_APP,
    WEBX_SERVICES_EMAIL,
    WEBX_SERVICES_MASKING_SMS,
    WEBX_SERVICES_NON_MASKING_SMS,
    WEBX_SERVICES_PACKAGE,
    WEBX_SERVICES_THEME
}
